### ISSUE TITLE
Refund Example Wrong

### ISSUE THREAD

**Issue by bobbonew** [nurelm/affirm-php#1]
Your refund example is wrong:

```
$amount = 399; /**< refund amount MUST be in cents */
$error = $affirm->refund_charge($charge_id, $refund);
```

The second line of code should read:

```
$amount = 399; /**< refund amount MUST be in cents */
$error = $affirm->refund_charge($charge_id, $amount);
```

(Since the variable $refund doesn't exist, it should instead take the second parameter **$amount** per the example)

**Comment by bobbonew** [comment]
Also in that same example, it states the refund amount must be in cents - should it not be:

```
$amount = 399.00; /**< refund amount MUST be in cents */
```

(Thanks for the hard work going into this class!)

**Comment by transitguru** [comment]
It in fact must be in cents per the Affirm. You are correct that the variable needs to be changed.
